/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaideep
 */
public class AddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    public AddCustomer() {
        initComponents();
        txtCompanyName.setVisible(false);
        labelCompanyName.setVisible(false);
        labelSSN.setVisible(false);
        txtSSN.setVisible(false);
        Connection conn=null;
        PreparedStatement pstmt=null;
        ResultSet rs=null;
        int Current_Cust_ID=0;
        try
        {
          conn=DbConnection.connect();
          pstmt=conn.prepareStatement("Select max(CustID) from customer;");
          rs=pstmt.executeQuery();
          while(rs.next())
          {
              Current_Cust_ID=rs.getInt("max(CustID)");
          }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }  
        txtCustID.setText(Integer.toString(Current_Cust_ID+1));
        txtCustID.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCustID = new javax.swing.JTextField();
        txtFNI = new javax.swing.JTextField();
        txtLN = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btnAddCust = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rbtnCompany = new javax.swing.JRadioButton();
        rbtnIndividual = new javax.swing.JRadioButton();
        labelSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        labelCompanyName = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CustomerID");

        jLabel2.setText("First Name Initial");

        jLabel3.setText("Last Name");

        jLabel4.setText("Phone");

        btnAddCust.setText("Add");
        btnAddCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustActionPerformed(evt);
            }
        });

        jLabel5.setText("Customer Type");

        buttonGroup1.add(rbtnCompany);
        rbtnCompany.setText("Company");
        rbtnCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCompanyActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnIndividual);
        rbtnIndividual.setText("Individual");
        rbtnIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnIndividualActionPerformed(evt);
            }
        });

        labelSSN.setText("SSN");

        labelCompanyName.setText("Company Name");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(labelSSN)
                    .addComponent(labelCompanyName))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCustID)
                        .addComponent(txtFNI)
                        .addComponent(txtLN)
                        .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rbtnCompany)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbtnIndividual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(txtSSN)
                        .addComponent(txtCompanyName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddCust, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbtnCompany)
                    .addComponent(rbtnIndividual))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompanyName)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCust)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustActionPerformed
        int CustID= Integer.parseInt(txtCustID.getText());
        String FNI= txtFNI.getText();
        String LN= txtLN.getText();
        String Phone=txtPhone.getText();
        String Comp_Name="";
        int SSN=0;
        if(rbtnCompany.isSelected())
        {
           Comp_Name=txtCompanyName.getText();   
        }
        else
        {
           SSN=Integer.parseInt(txtSSN.getText());  
        }
        Connection conn=null;
        PreparedStatement pstmt=null;
        try
        {
            conn=DbConnection.connect();
            pstmt=conn.prepareStatement("insert into Customer values(?,?,?,?)");
            pstmt.setInt(1,CustID);
            pstmt.setString(2,FNI);
            pstmt.setString(3,LN);
            pstmt.setString(4,Phone);
            int a=pstmt.executeUpdate();
            int b=0;
            if(rbtnCompany.isSelected())
            {
                conn=DbConnection.connect();
                pstmt=conn.prepareStatement("insert into Company values(?,?)");
                pstmt.setString(1,Comp_Name);
                pstmt.setInt(2,CustID);
                b=pstmt.executeUpdate();
            }
            else
            {
                conn=DbConnection.connect();
                pstmt=conn.prepareStatement("insert into Individual values(?,?)");
                pstmt.setInt(1,SSN);
                pstmt.setInt(2,CustID);
                b=pstmt.executeUpdate();
            }
            if(a>0&&b>0)
            {
                JOptionPane.showMessageDialog(null,"Record Added");
            }
            else
            {
                 JOptionPane.showMessageDialog(null,"Record Not Added");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        finally
        {
            try
            {
                conn.close();
                pstmt.close();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnAddCustActionPerformed

    private void rbtnIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnIndividualActionPerformed
        txtCompanyName.setVisible(false);
        labelCompanyName.setVisible(false);
        labelSSN.setVisible(true);
        txtSSN.setVisible(true);
    }//GEN-LAST:event_rbtnIndividualActionPerformed

    private void rbtnCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCompanyActionPerformed
        txtSSN.setVisible(false);
        labelSSN.setVisible(false);
        txtCompanyName.setVisible(true);
        labelCompanyName.setVisible(true);
    }//GEN-LAST:event_rbtnCompanyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
        new Admin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCust;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelCompanyName;
    private javax.swing.JLabel labelSSN;
    private javax.swing.JRadioButton rbtnCompany;
    private javax.swing.JRadioButton rbtnIndividual;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtCustID;
    private javax.swing.JTextField txtFNI;
    private javax.swing.JTextField txtLN;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables
}
