/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaideep
 */
public class AddOwner extends javax.swing.JFrame {

    /**
     * Creates new form AddOwner
     */
    public AddOwner() {
        initComponents();
        txtBname.setVisible(false);
        labelBname.setVisible(false);
        labelSSN.setVisible(false);
        txtSSN.setVisible(false);
        txtEname.setVisible(false);
        labelEname.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtOwner_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbtnBank = new javax.swing.JRadioButton();
        rbtnSolo = new javax.swing.JRadioButton();
        rbtnEnterprize = new javax.swing.JRadioButton();
        labelBname = new javax.swing.JLabel();
        txtBname = new javax.swing.JTextField();
        labelSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        labelEname = new javax.swing.JLabel();
        txtEname = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Owner ID");

        jLabel2.setText("Address");

        jLabel3.setText("Owner Type");

        buttonGroup1.add(rbtnBank);
        rbtnBank.setText("Bank");
        rbtnBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBankActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnSolo);
        rbtnSolo.setText("Solo");
        rbtnSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSoloActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnEnterprize);
        rbtnEnterprize.setText("Enterprize");
        rbtnEnterprize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEnterprizeActionPerformed(evt);
            }
        });

        labelBname.setText("Bank Name");

        labelSSN.setText("SSN");

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        labelEname.setText("Enterprize Name");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(txtOwner_ID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBname)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addComponent(labelEname)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBname, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnBank)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnSolo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnEnterprize))
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEname, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOwner_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnBank)
                        .addComponent(rbtnSolo)
                        .addComponent(rbtnEnterprize)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBname)
                    .addComponent(txtBname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(jButton1))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       int Owner_ID= Integer.parseInt(txtOwner_ID.getText());
       String Address= txtAddress.getText();
       String Bname="",Ename="";
       int SSN=0;
       if(rbtnBank.isSelected())
       {
           Bname=txtBname.getText();
       }
       else if(rbtnSolo.isSelected())
        {
           SSN=Integer.parseInt(txtSSN.getText());
        }
        else
        {
           Ename=txtEname.getText();
        }
        Connection conn=null;
        PreparedStatement pstmt=null;
        try
        {
            conn=DbConnection.connect();
            pstmt=conn.prepareStatement("insert into Owner values(?,?)");
            pstmt.setInt(1,Owner_ID);
            pstmt.setString(2,Address);
            int a=pstmt.executeUpdate();
            int b=0;
            if(rbtnBank.isSelected())
            {
                conn=DbConnection.connect();
                pstmt=conn.prepareStatement("insert into Bank values(?,?)");
                pstmt.setString(1,Bname);
                pstmt.setInt(2,Owner_ID);
                b=pstmt.executeUpdate();
            }
            else if(rbtnSolo.isSelected())
            {
                conn=DbConnection.connect();
                pstmt=conn.prepareStatement("insert into solo values(?,?)");
                pstmt.setInt(1,SSN);
                pstmt.setInt(2,Owner_ID);
                b=pstmt.executeUpdate();
            }
            else
            {
                conn=DbConnection.connect();
                pstmt=conn.prepareStatement("insert into Enterprize values(?,?)");
                pstmt.setString(1,Ename);
                pstmt.setInt(2,Owner_ID);
                b=pstmt.executeUpdate();
            }
            if(a>0&&b>0)
            {
                JOptionPane.showMessageDialog(null,"Record Added");
            }
            else
            {
               JOptionPane.showMessageDialog(null,"Record Not Added");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        finally
        {
            try
            {
                conn.close();
                pstmt.close();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void rbtnBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnBankActionPerformed
        txtBname.setVisible(true);
        labelBname.setVisible(true);
        labelSSN.setVisible(false);
        txtSSN.setVisible(false);
        txtEname.setVisible(false);
        labelEname.setVisible(false);
    }//GEN-LAST:event_rbtnBankActionPerformed

    private void rbtnSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSoloActionPerformed
        txtBname.setVisible(false);
        labelBname.setVisible(false);
        labelSSN.setVisible(true);
        txtSSN.setVisible(true);
        txtEname.setVisible(false);
        labelEname.setVisible(false);
    }//GEN-LAST:event_rbtnSoloActionPerformed

    private void rbtnEnterprizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEnterprizeActionPerformed
        txtBname.setVisible(false);
        labelBname.setVisible(false);
        labelSSN.setVisible(false);
        txtSSN.setVisible(false);
        txtEname.setVisible(true);
        labelEname.setVisible(true);
    }//GEN-LAST:event_rbtnEnterprizeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
        new Admin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOwner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelBname;
    private javax.swing.JLabel labelEname;
    private javax.swing.JLabel labelSSN;
    private javax.swing.JRadioButton rbtnBank;
    private javax.swing.JRadioButton rbtnEnterprize;
    private javax.swing.JRadioButton rbtnSolo;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBname;
    private javax.swing.JTextField txtEname;
    private javax.swing.JTextField txtOwner_ID;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables
}
