/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaideep
 */
public class UpdateCar extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCar
     */
    public UpdateCar() {
        initComponents();
        txtModel.setVisible(false);
        txtYear.setVisible(false);
        txtOID.setVisible(false);
        txtDR.setVisible(false);
        txtWR.setVisible(false);
        txtCar_type.setVisible(false);
        lblCar_type.setVisible(false);
        lblModel.setVisible(false);
        lblYear.setVisible(false);
        lblOID.setVisible(false);
        lblDR.setVisible(false);
        lblWR.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCar_type = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtVehicle_ID = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        lblDR = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        txtDR = new javax.swing.JTextField();
        lblOID = new javax.swing.JLabel();
        lblWR = new javax.swing.JLabel();
        txtOID = new javax.swing.JTextField();
        txtWR = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        txtCar_type = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCar_type.setText("Car Type");

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Vehicle ID");

        lblModel.setText("Model");

        lblYear.setText("Year");

        lblDR.setText("Daily Rate");

        txtDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDRActionPerformed(evt);
            }
        });

        lblOID.setText("Owner ID");

        lblWR.setText("Weekly Rate");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDR)
                    .addComponent(lblOID)
                    .addComponent(jLabel1)
                    .addComponent(lblModel)
                    .addComponent(lblYear)
                    .addComponent(lblCar_type)
                    .addComponent(lblWR))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOID)
                    .addComponent(txtCar_type)
                    .addComponent(txtDR)
                    .addComponent(txtWR)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModel)
                            .addComponent(txtYear, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtVehicle_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtVehicle_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCar_type)
                    .addComponent(txtCar_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDR, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWR))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnUpdate)
                    .addComponent(jButton2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtModel.setVisible(true);
        txtYear.setVisible(true);
        txtOID.setVisible(true);
        txtModel.setEditable(false);
        txtYear.setEditable(false);
        txtOID.setEditable(false);
        txtDR.setVisible(true);
        txtWR.setVisible(true);
        txtCar_type.setVisible(true);
        txtCar_type.setEditable(false);
        lblCar_type.setVisible(true);
        lblModel.setVisible(true);
        lblYear.setVisible(true);
        lblOID.setVisible(true);
        lblDR.setVisible(true);
        lblWR.setVisible(true);
        int VehicleID=0;
        VehicleID=Integer.parseInt(txtVehicle_ID.getText());
        String Model="";
        Connection conn=null;
        PreparedStatement pstmt=null;
        ResultSet rs=null;
        try
        {
          conn=DbConnection.connect();
          pstmt=conn.prepareStatement("select Vehicle_ID,Model,Year,OID,Car_type,Daily_Rate,Weekly_Rate from cars as c natural join (select mid as Vehicle_ID, mdr as Daily_Rate, mwr as Weekly_rate from medium union all select * from compact union all select * from large union all select * from suv union all select * from van union all select * from truck) as d where Vehicle_ID=?;");
          pstmt.setInt(1,VehicleID);
          rs=pstmt.executeQuery();
          while(rs.next())
          {
              txtVehicle_ID.setText(Integer.toString(rs.getInt("Vehicle_ID")));
              txtModel.setText(rs.getString("Model"));
              txtYear.setText(Integer.toString(rs.getInt("Year")));
              txtOID.setText(Integer.toString(rs.getInt("OID")));
              txtCar_type.setText(rs.getString("Car_type"));
              txtDR.setText(Integer.toString(rs.getInt("Daily_Rate")));
              txtWR.setText(Integer.toString(rs.getInt("Weekly_Rate")));
          }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Connection conn=null;
        int a=0;
        int DR=Integer.parseInt(txtDR.getText());
        int WR=Integer.parseInt(txtWR.getText());
        int Vehicle_ID=Integer.parseInt(txtVehicle_ID.getText());
        String car_type=txtCar_type.getText();
        PreparedStatement pstmt=null;
        try
        {
            conn=DbConnection.connect();
            if(car_type.equalsIgnoreCase("Compact"))
            {
                pstmt=conn.prepareStatement("update compact set CDR=? ,CWR= ? where CID=?");
                pstmt.setInt(1,DR);
                pstmt.setInt(2,WR);
                pstmt.setInt(3,Vehicle_ID);
                a=pstmt.executeUpdate();
            }
            else if(car_type.equalsIgnoreCase("Medium"))
            {
                pstmt=conn.prepareStatement("update Medium set MDR=? ,MWR= ? where MID=?");
                pstmt.setInt(1,DR);
                pstmt.setInt(2,WR);
                pstmt.setInt(3,Vehicle_ID);
                a=pstmt.executeUpdate();
            }
            else if(car_type.equalsIgnoreCase("Large"))
            {
                 pstmt=conn.prepareStatement("update Large set LDR=? ,LWR= ? where LID=?");
                pstmt.setInt(1,DR);
                pstmt.setInt(2,WR);
                pstmt.setInt(3,Vehicle_ID);
                a=pstmt.executeUpdate();
            }
            else if(car_type.equalsIgnoreCase("SUV"))
            {
                 pstmt=conn.prepareStatement("update SUV set SDR=? ,SWR= ? where SID=?");
                pstmt.setInt(1,DR);
                pstmt.setInt(2,WR);
                pstmt.setInt(3,Vehicle_ID);
                a=pstmt.executeUpdate();
            }
            else if(car_type.equalsIgnoreCase("Truck"))
            {
                pstmt=conn.prepareStatement("update Truck set TDR=? ,TWR= ? where TID=?");
                pstmt.setInt(1,DR);
                pstmt.setInt(2,WR);
                pstmt.setInt(3,Vehicle_ID);
                a=pstmt.executeUpdate();
            }
            else
            {
                pstmt=conn.prepareStatement("update Van set VDR=? ,VWR= ? where VID=?");
                pstmt.setInt(1,DR);
                pstmt.setInt(2,WR);
                pstmt.setInt(3,Vehicle_ID);
                a=pstmt.executeUpdate();
            }
                if(a>0)
                {
                    JOptionPane.showMessageDialog(null,"Record Updated");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Record Not Updated");
                }
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDRActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.hide();
        new Admin().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCar_type;
    private javax.swing.JLabel lblDR;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOID;
    private javax.swing.JLabel lblWR;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtCar_type;
    private javax.swing.JTextField txtDR;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOID;
    private javax.swing.JTextField txtVehicle_ID;
    private javax.swing.JTextField txtWR;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
